<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <RootNamespace>LwpTerm.Connections</RootNamespace>
    <AssemblyName>LwpTerm.Connections</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\LwpTerm.Core\LwpTerm.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="8.0.2" />
  </ItemGroup>

</Project>
